<?php

class Belvg_Import_Model_Resource_Setup extends Mage_Eav_Model_Entity_Setup
{
    /**
     * @return array
     */
    public function getDefaultEntities()
    {
        return array(
            'catalog_product' => array(
                'entity_model'      => 'catalog/product',
                'attribute_model'   => 'catalog/resource_eav_attribute',
                'table'             => 'catalog/product',
                'additional_attribute_table' => 'catalog/eav_attribute',
                'entity_attribute_collection' => 'catalog/product_attribute_collection',
                'attributes'        => array(
                    'mhsws_uid' => array(
                        'type'                       => 'text',
                        'label'                      => 'UID',
                        'input'                      => 'text',
                        'unique'                     => true,
                        'sort_order'                 => 14,
                        'is_searchable'              => false,
                        'is_comparable'              => false,
                        'visible_in_advanced_search' => false,
                        'visible'                    => false,
                        'visible_on_front'           => false,
                        'required'                   => false,
                    ),
                    'mhsws_department' => array(
                        'type'                       => 'text',
                        'label'                      => 'Department',
                        'input'                      => 'text',
                        'unique'                     => false,
                        'sort_order'                 => 15,
                        'is_searchable'              => 1,
                        'is_comparable'              => 0,
                        'is_filterable'              => 1,
                        'is_filterable_in_search'    => 1,
                        'visible_in_advanced_search' => false,
                        'visible'                    => false,
                        'visible_on_front'           => false,
                        'required'                   => false,
                        'is_filterable'              => true,
                    ),
                    'mhsws_cost' => array(
                        'type'                       => 'decimal',
                        'label'                      => 'Cost',
                        'input'                      => 'text',
                        'unique'                     => false,
                        'sort_order'                 => 16,
                        'is_searchable'              => 1,
                        'is_comparable'              => 1,
                        'visible_in_advanced_search' => 0,
                        'visible'                    => false,
                        'visible_on_front'           => false,
                        'required'                   => false,
                    ),
                    'mhsws_style' => array(
                        'type'                       => 'text',
                        'label'                      => 'Style',
                        'input'                      => 'text',
                        'unique'                     => false,
                        'sort_order'                 => 17,
                        'is_searchable'              => 1,
                        'is_comparable'              => 0,
                        'visible_in_advanced_search' => false,
                        'visible'                    => false,
                        'visible_on_front'           => false,
                        'required'                   => false,
                    ),
                    'mhsws_brand' => array(
                        'type'                       => 'text',
                        'label'                      => 'Brand',
                        'input'                      => 'select',
                        'unique'                     => false,
                        'sort_order'                 => 18,
                        'is_searchable'              => 1,
                        'is_comparable'              => 0,
                        'is_filterable'              => 1,
                        'is_filterable_in_search'    => 1,
                        'visible_in_advanced_search' => false,
                        'visible_on_front'        => 1,
                        'required'                   => false,
                        'filterable'                 => true,
                    ),
                    'mhsws_color' => array(
                        'type'                       => 'text',
                        'label'                      => 'Color',
                        'input'                      => 'select',
                        'unique'                     => false,
                        'sort_order'                 => 19,
                        'is_searchable'              => 1,
                        'is_comparable'              => 0,
                        'is_filterable'              => 1,
                        'is_filterable_in_search'    => 1,
                        'visible_in_advanced_search' => false,
                        'required'                   => false,
                        'filterable'                 => true,
                        'is_configurable'            => true,
                        'visible_on_front'        => TRUE,
                        'visible'                    => TRUE,
                        'searchable'                 => TRUE,
                    ),
                    'mhsws_size' => array(
                        'type'                       => 'text',
                        'label'                      => 'Size',
                        'input'                      => 'select',
                        'unique'                     => false,
                        'sort_order'                 => 19,
                        'is_searchable'              => 1,
                        'is_comparable'              => 0,
                        'is_filterable'              => 1,
                        'is_filterable_in_search'    => 1,
                        'visible_in_advanced_search' => false,
                        'visible_on_front'        => 1,
                        'required'                   => false,
                        'filterable'                 => true,
                        'is_configurable'            => true,
                    ),
                    'mhsws_size2' => array(
                        'type'                       => 'text',
                        'label'                      => 'Size',
                        'input'                      => 'select',
                        'unique'                     => false,
                        'sort_order'                 => 20,
                        'is_searchable'              => 1,
                        'is_comparable'              => 0,
                        'is_filterable'              => 1,
                        'is_filterable_in_search'    => 1,
                        'visible_in_advanced_search' => false,
                        'visible_on_front'        => 1,
                        'required'                   => false,
                        'filterable'                 => true,
                        'is_configurable'            => true,
                    ),
                    'mhsws_category' => array(
                        'type'                       => 'text',
                        'label'                      => 'Category',
                        'input'                      => 'text',
                        'unique'                     => false,
                        'sort_order'                 => 21,
                        'is_searchable'              => 1,
                        'is_comparable'              => 0,
                        'is_filterable'              => 1,
                        'is_filterable_in_search'    => 1,
                        'visible_in_advanced_search' => false,
                        'visible_on_front'        => true,
                        'required'                   => false,
                        'filterable'                 => true,
                    ),
                    'mhsws_fabric' => array(
                        'type'                       => 'text',
                        'label'                      => 'Fabric',
                        'input'                      => 'text',
                        'unique'                     => false,
                        'sort_order'                 => 22,
                        'is_searchable'              => 1,
                        'is_comparable'              => 0,
                        'is_filterable'              => 1,
                        'is_filterable_in_search'    => 1,
                        'visible_in_advanced_search' => false,
                        'visible_on_front'        => 1,
                        'required'                   => false,
                        'filterable'                 => true,
                    ),
                )
            ),

            'catalog_category'               => array(
                'entity_model'                   => 'catalog/category',
                'attribute_model'                => 'catalog/resource_eav_attribute',
                'table'                          => 'catalog/category',
                'additional_attribute_table'     => 'catalog/eav_attribute',
                'entity_attribute_collection'    => 'catalog/category_attribute_collection',
                'default_group'                  => 'General Information',
                'attributes'                     => array(
                    'mhsws_alias' => array(
                        'type'                       => 'varchar',
                        'label'                      => 'mhsws alias',
                        'input'                      => 'text',
                        'sort_order'                 => 70,
                        'global'                     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'group'                      => 'General Information',
                        'required'                   => false,
                        'used_in_product_listing'    => true,
                        'is_configurable'            => false,
                    ),
                )
            ),

        );
    }
}