<?php
//Belvg MHSWS Connector
?>
<button style="margin:10px" id="belvg_qty_button" type="button" class="scalable add" style="">
    <span>
        <span>Update Qty</span>
    </span>
</button>
<div id="belvg_qty_console" style="padding:10px 0 10px 0"></div>
<script>
    (function($) {
        $('#belvg_qty_button').click(function() {
            $('#belvg_qty_console').html('');
            $('#belvg_qty_button').attr('disabled', 'disabled').addClass('disabled');
            runMhswsQtyUpdate();
        });

        var runMhswsQtyUpdate = function() {
            var panel = $('<div>')
                .attr('id', 'mhsws_qty_panel')
                .attr('style', 'padding:10px;background-color:#fff;border:1px solid #ddd;margin-bottom:7px;')
                .html('<b>run...</b>');
            $('#belvg_qty_console').append(panel);
            var iteration = 0;

            sendChromeAjaxQtyQuery(iteration);
        }

        var sendChromeAjaxQtyQuery = function(iteration, cursor) {
            $('#mhsws_qty_panel').append('<br>-------------Iteration #' + iteration + '-------------');
            $.ajax({
                url: '<?php echo Mage::getUrl('import/index/update_qty') ?>',
                data: {iteration: iteration, cursor: cursor},
                success: function(data) {

                    jdata = $.parseJSON(data);
                    if (jdata.error == 1) {
                        $('#mhsws_qty_panel').html('Error. Something went wrong!');

                        showQtyLog(jdata.log);

                        $('#belvg_qty_button').removeAttr('disabled').removeClass('disabled');
                        return false;
                    } else {
                        if (jdata.waiting == 1) {
                            showQtyLog(jdata.log);

                            sendChromeAjaxQtyQuery(iteration, jdata.cursor);
                        } else {
                            if (jdata.length == 0) {
                                showQtyLog(jdata.log);

                                $('#mhsws_qty_panel').append('<br>Data [batch] is empty!');

                                $('#belvg_qty_button').removeAttr('disabled').removeClass('disabled');
                            } else {
                                showQtyLog(jdata.log);

                                sendChromeAjaxQtyQuery(++iteration, jdata.cursor);
                            }
                        }

                    }
                },
                error: function(){
                    $('#mhsws_qty_panel').html('Ajax Error...');
                }
            });
        }

        var showQtyLog = function (arr_log){
            arr_log.forEach(function(entry) {
                $('#mhsws_qty_panel').append('<br><b>' + entry + '</b>');
            });
        }

    })(jQuery);
</script>